[versions]
kotlin = "2.2.10"
kotlinx = "1.10.2"
kotest = "6.1.3"
junit = "5.14.3"
koin = "4.1.1"
quarkus = "3.31.3"
jakarta = "4.1.0"
spring-boot-2x = "2.7.18"
spring-boot-3x = "3.5.10"
spring-boot-4x = "4.0.2"
ktlint = "1.8.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
org-reflections = { module = "org.reflections:reflections", version = "0.10.2" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
quarkusBom = { module = "io.quarkus:quarkus-bom", version.ref = "quarkus" }
quarkus-arc = { module = "io.quarkus:quarkus-arc", version.ref = "quarkus" }
jakarta-enterpise-cdi-api = { module = "jakarta.enterprise:jakarta.enterprise.cdi-api", version.ref = "jakarta" }

spring-boot-4x-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot-4x" }
spring-boot-4x-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot-4x" }

spring-boot-3x-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot-3x" }
spring-boot-3x-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot-3x" }

spring-boot-2x-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot-2x" }
spring-boot-2x-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot-2x" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }

# test
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-table = { module = "io.kotest:kotest-assertions-table", version.ref = "kotest" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5", version.ref = "quarkus" }

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.7" }
testLogger = { id = "com.adarshr.test-logger", version = "4.0.0" }
spotless = { id = "com.diffplug.spotless", version = "8.2.1" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
